import Head from "next/head";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Spotify</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.png' />
            </Head>
            <h1 className='text-green-500 font-bold'>
                This is the starter code for Spotify
            </h1>
            <main>
                {/* Sidebar */}
                {/* Center */}
            </main>
            <div>{/* Player */}</div>
        </div>
    );
}
