import React from "react";

function Login() {
    return (
        <div>
            <Head>
                <title>Spotify</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.png' />
            </Head>
            Login Page
        </div>
    );
}

export default Login;
