import React from "react";
import { getProviders, signIn } from "next-auth/react";
import Head from "next/head";

function Login({ providers }) {
    return (
        <div className='flex flex-col bg-black min-h-screen justify-center items-center w-full'>
            <Head>
                <title>Spotify</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.png' />
            </Head>
            <img
                src='https://links.papareact.com/9xl'
                alt='A 9xl logo of Spotify'
                className='w-52 mb-5'
            />
            {Object.values(providers).map((provider) => (
                <div key={provider.name}>
                    <button
                        className='bg-[#18D860] text-white p-5 rounded-full'
                        onClick={() =>
                            signIn(provider.id, { callbackUrl: "/" })
                        }>
                        Login with {provider.name}
                    </button>
                </div>
            ))}
        </div>
    );
}

export default Login;

export async function getServerSideProps() {
    const providers = await getProviders();
    return {
        props: {
            providers,
        },
    };
}
